"use client"

import * as React from "react"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Globe, FileText, ArrowRight, AlertTriangle, X } from "lucide-react"
import { cn } from "@/lib/utils"

export type InputData = {
  email: string
  sourceInput: string
  inputType: "WEBSITE" | "MANUAL"
}

interface InputStepProps {
  onSubmit: (data: InputData) => void
  isLoading: boolean
  initialTab?: "website" | "manual"
  initialText?: string
  initialEmail?: string
  scanError?: string | null
  onClearScanError?: () => void
}

export function InputStep({ 
  onSubmit, 
  isLoading, 
  initialTab = "website", 
  initialText = "", 
  initialEmail = "",
  scanError,
  onClearScanError
}: InputStepProps) {
  const [tab, setTab] = React.useState<"website" | "manual">(initialTab)
  const [email, setEmail] = React.useState(initialEmail)
  const [url, setUrl] = React.useState("")
  const [text, setText] = React.useState(initialText)
  const [error, setError] = React.useState("")

  React.useEffect(() => {
    setTab(initialTab)
  }, [initialTab])

  React.useEffect(() => {
    if (initialText) setText(initialText)
  }, [initialText])

  React.useEffect(() => {
    if (initialEmail) setEmail(initialEmail)
  }, [initialEmail])

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    setError("")

    if (!email || !email.includes("@")) {
      setError("Please enter a valid email address.")
      return
    }

    if (tab === "website") {
      if (!url.trim()) {
        setError("Please enter a website URL.")
        return
      }
      onSubmit({
        email: email.trim(),
        sourceInput: url.trim(),
        inputType: "WEBSITE",
      })
    } else {
      if (!text.trim() || text.trim().length < 10) {
        setError("Please provide a description of at least 10 characters.")
        return
      }
      onSubmit({
        email: email.trim(),
        sourceInput: text.trim(),
        inputType: "MANUAL",
      })
    }
  }

  return (
    <Card className="bg-white rounded-[2rem] p-8 md:p-12 shadow-2xl shadow-black/5 border-none w-full max-w-2xl mx-auto text-left">
      <div className="text-center mb-8">
        <h2 className="text-3xl font-black mb-2 tracking-tight text-foreground">
          Import Your <span className="text-brand">Brand DNA</span>
        </h2>
        <p className="text-muted-foreground text-sm">
          Get a comprehensive Brand Guidelines document generated by AI in seconds.
        </p>
      </div>

      {/* Tabs Switcher */}
      <div className="grid grid-cols-2 bg-muted/50 p-1.5 rounded-2xl mb-8 w-full max-w-xl mx-auto border border-border">
        <button
          type="button"
          onClick={() => {
            setTab("website")
            setError("")
            onClearScanError?.()
          }}
          className={cn(
            "flex items-center justify-center gap-2 py-3.5 rounded-xl font-bold text-sm transition-all whitespace-nowrap border",
            tab === "website" ? "bg-white text-brand shadow-sm border-border" : "bg-transparent text-muted-foreground hover:text-foreground border-transparent"
          )}
        >
          <Globe size={16} /> I have a website
        </button>
        <button
          type="button"
          onClick={() => {
            setTab("manual")
            setError("")
          }}
          className={cn(
            "flex items-center justify-center gap-2 py-3.5 rounded-xl font-bold text-sm transition-all whitespace-nowrap border",
            tab === "manual" ? "bg-white text-brand shadow-sm border-border" : "bg-transparent text-muted-foreground hover:text-foreground border-transparent"
          )}
        >
          <FileText size={16} /> Describe your brand
        </button>
      </div>

      {scanError && (
        <div className="bg-amber-50/80 border border-amber-200/60 rounded-2xl p-4 flex gap-3 text-left mb-6 animate-fade-in relative">
          <div className="w-8 h-8 rounded-full bg-amber-100 flex items-center justify-center text-amber-800 shrink-0">
            <AlertTriangle size={16} />
          </div>
          <div className="space-y-1 pr-6">
            <h4 className="text-sm font-black text-amber-900 leading-none">
              Website Scan Failed
            </h4>
            <p className="text-xs text-amber-800 leading-relaxed font-medium">
              We couldn't extract enough content from your website. Please paste your about page, brand details, or describe your company manually below so we can generate your Brand DNA.
            </p>
          </div>
          <button
            type="button"
            onClick={onClearScanError}
            className="absolute top-4 right-4 text-amber-500 hover:text-amber-800 transition-colors"
          >
            <X size={14} />
          </button>
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Email Field */}
        <div>
          <label className="text-[10px] font-black text-muted-foreground uppercase tracking-widest mb-2 block">
            Email Address
          </label>
          <input
            type="email"
            required
            className="w-full bg-muted/30 border-2 border-border rounded-2xl px-4 py-3 text-sm focus:border-brand outline-none transition-all text-foreground"
            placeholder="you@company.com"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
        </div>

        {/* Dynamic Fields */}
        {tab === "website" ? (
          <div>
            <label className="text-[10px] font-black text-muted-foreground uppercase tracking-widest mb-2 block">
              Website URL
            </label>
            <input
              type="text"
              className="w-full bg-muted/30 border-2 border-border rounded-2xl px-4 py-3 text-sm focus:border-brand outline-none transition-all text-foreground"
              placeholder="example.com"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
            />
          </div>
        ) : (
          <div>
            <label className="text-[10px] font-black text-muted-foreground uppercase tracking-widest mb-2 block">
              Describe your Brand
            </label>
            <textarea
              className="w-full bg-muted/30 border-2 border-border rounded-2xl px-4 py-3 text-sm focus:border-brand outline-none transition-all resize-none text-foreground"
              placeholder="Paste your Instagram bio, About Us page content, or just tell us what your brand does in 2-3 sentences..."
              rows={5}
              value={text}
              onChange={(e) => setText(e.target.value)}
            />
          </div>
        )}

        {error && <p className="text-red-500 text-xs font-bold text-center">{error}</p>}

        <Button
          type="submit"
          disabled={isLoading}
          className="w-full h-14 bg-brand hover:bg-brand-dark text-white font-black rounded-2xl shadow-lg shadow-brand/20 flex items-center justify-center gap-2 text-base transition-all active:scale-98 disabled:opacity-50"
        >
          {isLoading ? (
            tab === "website" 
              ? "Analyzing website & pre-filling workbook..." 
              : "Analyzing description & pre-filling workbook..."
          ) : "Generate Brand DNA"}
          {!isLoading && <ArrowRight size={18} />}
        </Button>
      </form>
    </Card>
  )
}
